### ISSUE TITLE
MQConnection can get into an unrecoverable state during startup

### ISSUE THREAD

**Issue by magnusbaeck** [jenkinsci/eiffel-broadcaster-plugin#81]
### Jenkins and plugins versions report

Custom Docker image based on Jenkins 2.346.3<br>
eiffel-broadcaster 2.4.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 18.04.6

### Reproduction steps

1. Install and configure the plugin on a Jenkins controller.
2. Restart the controller.

### Expected Results

Plugin fires up nicely and starts publishing events.

### Actual Results

The plugin attempts to send an event before [EiffelBroadcasterConfig](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/eiffel-broadcaster-2.4.0/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java), a GlobalConfiguration subclass, has been configured. At that time the AMQP URL is still null and we get an NPE in the MQConnection#messageQueueThread thread.

```
2022-12-01 08:26:29.292+0000 [id=104]   SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (Thread-17/104) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
        at java.base/java.net.URI$Parser.parse(URI.java:3104)
        at java.base/java.net.URI.<init>(URI.java:600)
        at com.rabbitmq.client.ConnectionFactory.setUri(ConnectionFactory.java:379)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.getConnectionFactory(MQConnection.java:349)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.getConnection(MQConnection.java:378)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.createChannel(MQConnection.java:301)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.sendMessages(MQConnection.java:252)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.lambda$addMessageToQueue$0(MQConnection.java:209)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Within a few seconds the configuration is in place, but because of another bug in [MQConnection#addMessageToQueue](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/eiffel-broadcaster-2.4.0/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java#L163) it attempts to restart the old dead thread instead of recreating it, resulting in another exception:

```
2022-12-01 08:26:35.250+0000 [id=53]    WARNING jenkins.util.Listeners#lambda$notify$0
java.lang.IllegalThreadStateException
        at java.base/java.lang.Thread.start(Thread.java:789)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.MQConnection.addMessageToQueue(MQConnection.java:180)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.Util.mustPublishEvent(Util.java:138)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.Util.mustPublishEvent(Util.java:159)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.Util.publishEvent(Util.java:171)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.RunListenerImpl.onCompleted(RunListenerImpl.java:131)
        at hudson.model.listeners.RunListener.lambda$fireCompleted$0(RunListener.java:207)
        at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
        at jenkins.util.Listeners.notify(Listeners.java:67)
        at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:205)
        at hudson.model.Run.execute(Run.java:1933)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
        at hudson.model.ResourceController.execute(ResourceController.java:101)
        at hudson.model.Executor.run(Executor.java:442)
```

### Anything else?

The NPE as well as the thread restart problem should be easy enough to fix, but the MQ Notifier plugin received a significant revamp of its AMQP sending code in https://github.com/jenkinsci/mq-notifier-plugin/pull/30 so we should port those changes here instead. This plugin basically started out as a fork of MQ Notifier so the patches should apply without too much trouble. That'll also bring a number of other improvements. We run MQ Notifier on the same host where we had issues with this plugin and MQ Notifier wasn't affected. It's of course possible that we only were lucky with MQ Notifier (such is the nature of race conditions) but I suspect the reason actually is more robustness in that plugin.

cc: @hampusjohansson1

**Comment by magnusbaeck** [comment]
What's really surprising is how we can even reach the message queue thread if the plugin hasn't been configured. To reach the message queue thread where the NPE occurs we have to call [Util.mustPublishEvent](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/eiffel-broadcaster-2.4.0/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java#L125-L141), and it explicitly checks if event publishing is enabled, and if it doesn't it bails immediately. If the plugin hasn't been initialized, why would the enable bool be anything but false? We can't possibly have been so unlucky that we were caught in the middle of the initialization so that the enable bool had been set to true but the AMQP URL hadn't been touched?
